# Saving and Loading Model for Future Use

In [24]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import pickle

In [3]:
years = np.arange(1990, 2021)
income_values = 35000 + 500 * (years - 1990)

df = pd.DataFrame({'Year': years, 'Per Capita Income (CAD)': income_values})

In [4]:
reg = linear_model.LinearRegression()
reg.fit(df[['Year']], df['Per Capita Income (CAD)'])

LinearRegression()

In [5]:
reg.coef_

array([500.])

In [6]:
reg.intercept_

-959999.9999999995

In [9]:
reg.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1540000.])

In [25]:
with open('model_pickle', 'wb') as file:
  pickle.dump(reg, file)

# Load the Model from File

We can also share the file with someone.

In [26]:
with open('model_pickle', 'rb') as file:
  model = pickle.load(file)

In [22]:
model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1540000.])